dynamixel_controllers:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 10

  first_position_controller:
    type: position_controllers/JointPositionController
    joint: joint1

  second_position_controller:
    type: position_controllers/JointPositionController
    joint: joint2

  third_position_controller:
    type: position_controllers/JointPositionController
    joint: joint3

  fourth_position_controller:
    type: position_controllers/JointPositionController
    joint: joint4

dynamixel_control_hw:
  loop_frequency: 1000
  cycle_time_error_threshold: 0.2
  serial_interface: /dev/ttyACM0
  baudrate: 1000000 # in bauds
  dynamixel_timeout: 0.05 # in seconds
  dynamixel_scanning: 0.05 # in seconds
  # correspondance between hardware IDs of the actuators and their names in ROS
  hardware_mapping:
    joint1: 6
    joint2: 7
    joint3: 4
    joint4: 2
  # offset to be added, in ticks, to the position of an actuator
  hardware_corrections:
    "6": 0
    "4": 0
